---
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "tbank-prometheus"
    # scheme defaults to 'http'.
    scheme: "http"
    # metrics_path defaults to '/metrics'
    # metrics_path: "tbank/metrics"

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
    scrape_timeout: 15s

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "tbank-oncall-notifier"
    # Override the global default and scrape targets from this job every 5 seconds.
    # Get "http://oncall.local:80/metrics": context deadline exceeded
    scrape_interval: 30s
    scrape_timeout: 30s
    metrics_path: "/metrics"

    static_configs:
      - targets:
          [
            "oncall.local",
            "192.168.58.2",
            "host.docker.internal",
            "oncall:9091",
          ]
